config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/create'

  get 'cart_items/update'

  get 'cart_items/destroy'

  get 'carts/show'

  devise_for :users

  resource :cart, only: [:show]
  resources :cart_items, only: [:create, :update, :destroy], defaults: { format: 'js' }

  resources :users, :only => [:show]

  resources :posts, :categories

  resources :posts do
    put :favorite, on: :member
  end

  resources :favorites, :only => [:index]

  resources :posts do
    resources :comments, module: :posts
  end

  resources :comments

  get 'posts/:id/delete_image', to: 'posts#delete_image', as: 'delete_post_image'

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  get 'welcome', to: 'pages#welcome' 

  root 'posts#index'
end

app/models/favorite_post.rb
class FavoritePost < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	
end

app/controllers/favorite_posts_controller.rb
class FavoritePostsController < ApplicationController
	load_and_authorize_resource
	
	def index
		@post = Post.find(params[:id])
	end

end

app/helpers/favorite_post_helper.rb
module FavoritePostHelper
end

app/views/favorite_post/index.html.erb
<div class="wrapper">
  <%= link_to "New post", new_post_path, class: "btn btn-default new-post-btn"%>
    <div class="post-container">
      <% @user.favorites.each do |post| %>
        <div class="col-xs-12">
          <div class="post-content">
            <div class="text-center">
              <div class="post-title">
                <h2 style="text-align: center"><%= link_to post.title, post_path(post), style: "color: black" %></h2>
                  </div>
                  <h6>Posted by <%= link_to post.user.username, post.user %> on: <%= post.created_at.strftime('%b %d, %Y') %></h6>
                  <%= link_to Category.find(post.category_id).name, category_path(post.category_id) %>
                </div>

                <div class="post-body">
                  <%= raw(post.body).truncate(358) %>
                </div>

                <div class="text-center">
                  <%= link_to "READ MORE", post_path(post), class: "btn btn-sm"%>
                </div>
                <hr>
                <div class="post-buttons">
                  <%= link_to "Edit", edit_post_path(post), class: "btn btn-default btn-sm" %>
                  <%= link_to "Delete", post_path(post),
                    method: :delete,
                    data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"%>
                  <div class="post-buttons-right" style="float: right">
                    <div class="favorite-button">
                      <% if current_user %>
                        <% if post.favorited_by.exists?(current_user.id) %>
                          <%= link_to favorite_post_path(post, type: "unfavorite"), method: :put, class: "btn btn-default btn-sm", title: "Remove from favorites" do %>
                          <span class="glyphicon glyphicon-star" style="color: #ffbb33"></span>
                          <% end %>
                        <% else %>
                          <%= link_to favorite_post_path(post, type: "favorite"), method: :put, class: "btn btn-default btn-sm", title: "Add to favorites" do %>
                          <span class="glyphicon glyphicon-star" style="color: grey"></span>
                          <% end %>
                        <% end %>
                      <% end %>
                      <div class="comment-button" style="float: right">
                        <%= link_to post_path(post, anchor: "comment-section"), class: "btn btn-default btn-sm", title: "Show comments" do %>
                        <span class="glyphicon glyphicon-comment" style="color: grey"></span>
                        <%= post.comments.count %>
                      <% end %>
                      </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
    <br>
    &nbsp;
    <% end %>
  </div>
</div>

app/views/favorite_post/post_id:integer.html.slim
h1 FavoritePost#post_id:integer
p Find me in app/views/favorite_post/post_id:integer.html.slim

app/views/favorite_post/user_id:integer.html.slim
h1 FavoritePost#user_id:integer
p Find me in app/views/favorite_post/user_id:integer.html.slim