config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/create'

  get 'cart_items/update'

  get 'cart_items/destroy'

  get 'carts/show'

  devise_for :users

  resource :cart, only: [:show]
  resources :cart_items, only: [:create, :update, :destroy], defaults: { format: 'js' }

  resources :users, :only => [:show]

  resources :posts, :categories

  resources :posts do
    put :favorite, on: :member
  end

  resources :favorites, :only => [:index]

  resources :posts do
    resources :comments, module: :posts
  end

  resources :comments

  get 'posts/:id/delete_image', to: 'posts#delete_image', as: 'delete_post_image'

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  get 'welcome', to: 'pages#welcome' 

  root 'posts#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new

    alias_action :create, :read, :update, :destroy, to: :crud
    alias_action :create, :update, :destroy, to: :cud

    if user.admin?
        can :crud, :all
    elsif user.moderator?
        can :crud, Post
        can :crud, Comment
        can :crud, FavoritePost
        can :crud, Category
        can :read, :all
        cannot :manage, User
    elsif user.member?
        can :read, :all
        can :crud, Post, user_id: user.id
        can :crud, Comment, user_id: user.id
        can :crud, FavoritePost, user_id: user.id
        can :read, Category
        can :crud, User, user_id: user.id
        cannot :cud, Category
    else
        can :read, Post
    end
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :post
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :order_id, uniqueness: { scope: :post_id, message: "Already in cart" }
  validate :post_present
  validate :order_present

  before_save :finalize

  def item_price
  	if persisted?
  		self[:item_price]
  	else
  		post.price
  	end
  end

  def total_price
  	item_price * quantity
  end

  private

  def post_present
  	if post.nil?
  		errors.add(:post, 'Post error')
  	end
  end

  def order_present
  	if order.nil?
  		errors.add(:order, 'Order missing')
  	end
  end

  def finalize
  	self[:item_price] = item_price
  	self[:total_price] = quantity * self[:item_price]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
	belongs_to :user
	belongs_to :post
end

app/models/favorite_post.rb
class FavoritePost < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	
end

app/models/order.rb
class Order < ActiveRecord::Base
  after_create :set_order_status
  before_save :update_subtotal
  belongs_to :order_status
  has_many :cart_items

  def subtotal
	 cart_items.collect { |i| i.valid? ? (i.quantity.to_i * i.item_price.to_f) : 0 }.sum
  end

private

  def set_order_status
    self.order_status_id = 1 if self.order_status_id.nil?
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
	has_many :favorite_posts
	has_many :favorited_by, through: :favorite_posts, source: :user
	has_many :comments, as: :commentable
	has_many :cart_items

	default_scope { where(active: true) }

	has_attached_file :image, styles: { thumb: "64x64#", small: "100x100#", medium: "350x350#", large: "700x700>" },
					:url  => "/assets/posts/:id/:style/:basename.:extension",
                  	:path => ":rails_root/public/assets/posts/:id/:style/:basename.:extension"

	validates_attachment_size :image, :less_than => 5.megabytes

	validates :category, presence: true

	validates :title, presence: true, length: { minimum: 5 }

	validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/png"] }

    #validates :price, numericality: { greater_than: 0 }

end

app/models/user.rb
class User < ActiveRecord::Base
	resourcify
  	rolify
	has_many :posts
	has_many :favorite_posts
	has_many :favorites, through: :favorite_posts, source: :post
	has_many :comments

	has_attached_file :avatar, styles: { thumb: "32x32#", small: "64x64#", medium: "350x350#", large: "700x700>" },
					:url  => "/assets/users/:id/:style/:basename.:extension",
                  	:path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"

	validates_attachment_size :avatar, :less_than => 5.megabytes

	validates :username, presence: true

	validates_attachment :avatar,
                     content_type: { content_type: ["image/jpeg", "image/png"] }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@cart_items = current_order.cart_items
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def welcome
		@recent_posts = Post.order("created_at DESC").limit(4)
		render layout: 'landing'
	end

	def about
		render pages: 'about'
	end

	def contact
		render pages: 'contact'
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	load_and_authorize_resource
	
	def index
		@posts = Post.order('created_at DESC')
		@cart_item = current_order.cart_items.new
	end

	def new
		@post = Post.new
		@categories = Category.all.map{|c| [ c.name, c.id ] }
	end

	def create
		@post = Post.new(post_params)
		@post.category_id = params[:category_id] 
		@post.user_id = current_user.id
		if @post.save
			flash.now[:notice] = "Created a post"
			redirect_to @post
		else
			flash.now[:alert] = "Error saving post!"
			render :new
		end
	end

	def edit
		@post = Post.find(params[:id])
		@categories = Category.all.collect{|c| [ c.name, c.id ] }
	end

	def update
		@categories = Category.all.map{|c| [ c.name, c.id ] }
		@post = Post.find_by_id(params[:id])
		@post.category_id = params[:category_id]
		@post.user_id = current_user.id
		if @post.update_attributes(post_params.except(:user_id))
			flash.now[:notice] = "Successfully updated post!"
			redirect_to post_path(@post)
		else
			flash.now[:alert] = "Error updating post!"
			render :edit
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def favorite
		@post = Post.find(params[:id])
		type = params[:type]
		if type == "favorite"
			current_user.favorites << @post
			redirect_to :back, notice: "Added #{@post.title} to favorites"
		elsif type == "unfavorite"
			current_user.favorites.delete(@post)
			redirect_to :back, notice: "Removed #{@post.title} from favorites"
		else
			redirect_to :back, notice: "Nothing"
		end	
	end

	def destroy
		if @post.destroy
			flash.now[:notice] = 'Post deleted!'
			redirect_to posts_path
		else
			flash.now[:alert] = 'Error!'
		end
	end

	def delete_image
		@post = Post.find(params[:id])
		@post.image = nil
		@post.save
		redirect_to @post
	end

	private

	def post_params
		params.require(:post).permit(:title, :body, :image, :user_id, :price)
	end

	def find_post
		@post = Post.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	include FontAwesome::Rails::IconHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def item_price
		"$" + price
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  ...
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catalog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel='stylesheet' href='vendor/assets/javascripts/mdb.min'></script>
  <link rel='stylesheet' href="vendor/assets/stylesheets/mdb.css">
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "/shared/navbar" %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="wrapper">
	<div class="content-section">
		<h3>About Us</h3>
		<h5>Created by Taras Misyurak</h5>
	</div>
</div>

app/views/shared/_cart_text.html.erb
<%= link_to "#{current_order.cart_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link cart-text" %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'posts' %>"><%= link_to "Posts", posts_path %></li>
        <li class="<%= 'active' if params[:controller] == 'categories' %>"><%= link_to "Categories", categories_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li><%= render partial: "/shared/cart_text" %></li>
      	 <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="<%= 'active' if params[:controller] == 'profiles' %>"><%= link_to 'Profile', user_path(current_user.id) %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>