config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/create'

  get 'cart_items/update'

  get 'cart_items/destroy'

  get 'carts/show'

  devise_for :users

  resource :cart, only: [:show]
  resources :cart_items, only: [:create, :update, :destroy], defaults: { format: 'js' }

  resources :users, :only => [:show]

  resources :posts, :categories

  resources :posts do
    put :favorite, on: :member
  end

  resources :favorites, :only => [:index]

  resources :posts do
    resources :comments, module: :posts
  end

  resources :comments

  get 'posts/:id/delete_image', to: 'posts#delete_image', as: 'delete_post_image'

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  get 'welcome', to: 'pages#welcome' 

  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
	has_many :favorite_posts
	has_many :favorited_by, through: :favorite_posts, source: :user
	has_many :comments, as: :commentable
	has_many :cart_items

	default_scope { where(active: true) }

	has_attached_file :image, styles: { thumb: "64x64#", small: "100x100#", medium: "350x350#", large: "700x700>" },
					:url  => "/assets/posts/:id/:style/:basename.:extension",
                  	:path => ":rails_root/public/assets/posts/:id/:style/:basename.:extension"

	validates_attachment_size :image, :less_than => 5.megabytes

	validates :category, presence: true

	validates :title, presence: true, length: { minimum: 5 }

	validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/png"] }

    #validates :price, numericality: { greater_than: 0 }

end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
	before_action :set_commentable

	private

	def set_commentable
		@commentable = Post.find(params[:post_id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	load_and_authorize_resource
	
	def index
		@posts = Post.order('created_at DESC')
		@cart_item = current_order.cart_items.new
	end

	def new
		@post = Post.new
		@categories = Category.all.map{|c| [ c.name, c.id ] }
	end

	def create
		@post = Post.new(post_params)
		@post.category_id = params[:category_id] 
		@post.user_id = current_user.id
		if @post.save
			flash.now[:notice] = "Created a post"
			redirect_to @post
		else
			flash.now[:alert] = "Error saving post!"
			render :new
		end
	end

	def edit
		@post = Post.find(params[:id])
		@categories = Category.all.collect{|c| [ c.name, c.id ] }
	end

	def update
		@categories = Category.all.map{|c| [ c.name, c.id ] }
		@post = Post.find_by_id(params[:id])
		@post.category_id = params[:category_id]
		@post.user_id = current_user.id
		if @post.update_attributes(post_params.except(:user_id))
			flash.now[:notice] = "Successfully updated post!"
			redirect_to post_path(@post)
		else
			flash.now[:alert] = "Error updating post!"
			render :edit
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def favorite
		@post = Post.find(params[:id])
		type = params[:type]
		if type == "favorite"
			current_user.favorites << @post
			redirect_to :back, notice: "Added #{@post.title} to favorites"
		elsif type == "unfavorite"
			current_user.favorites.delete(@post)
			redirect_to :back, notice: "Removed #{@post.title} from favorites"
		else
			redirect_to :back, notice: "Nothing"
		end	
	end

	def destroy
		if @post.destroy
			flash.now[:notice] = 'Post deleted!'
			redirect_to posts_path
		else
			flash.now[:alert] = 'Error!'
		end
	end

	def delete_image
		@post = Post.find(params[:id])
		@post.image = nil
		@post.save
		redirect_to @post
	end

	private

	def post_params
		params.require(:post).permit(:title, :body, :image, :user_id, :price)
	end

	def find_post
		@post = Post.find(params[:id])
	end

end

app/helpers/posts_helper.rb
module PostsHelper
	def item_price
		"$" + price
	end
end

app/views/posts/_form.html.erb
<div class="content">
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <% if @post.image? %>
   <% link_to image_tag(@post.image.url(:small), class: 'media-object'), @post.image.url, target: '_blank' %>
   <% link_to "Remove image", post_path(@post),
      method: :delete_image,
      data: { confirm: 'Are you sure?' } %>
  <% end %>

  <div class="form-group">
    <p>Add an image</p>
    <%= f.file_field :image %>
  </div>
  <div>
  <%= select_tag(:category_id, options_for_select(@categories, @post.category_id), { :prompt => "Select category", :class => "btn btn-default" }) %>
  </div>
  <br>
  <div class="form-group">
    <h6>Enter price</h6>
    <%= f.text_field :price, class: 'text-field form-control', style: 'width: 100px', min: 0, step: '0.5' %>
    <h6><span style="color: orange">If blank price will be set to free!</span></h6>
  </div>

  <div class="form-group">
    <% if current_page?(new_post_path) %>
      <%= f.submit "Create Post", class: "btn btn-default" %>
    <% elsif current_page?(edit_post_path) %>
      <%= f.submit "Update Post", class: "btn btn-default" %>
    <% end %>
  </div>
<% end %>

<% if current_page?(new_post_path) %>
  <%= link_to "Back", posts_path, class: "btn btn-default" %>
<% elsif current_page?(edit_post_path(@post)) %>
  <%= link_to "Back to post", post_path(@post), class: "btn btn-default" %>
<% end %>
</div>

app/views/posts/_post_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= post.title %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for cart_item, remote: true do |f| %>
      <h4 class="text-right">Item Price: <span style="color: green"><%= number_to_currency post.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1, style: "width: 50px"%>
          <div class="input-group-btn">
            <%= f.hidden_field :post_id, value: post.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-12">
			<h1>Edit post</h1>

			<%= render "posts/form" %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-1 col-md-offset-11 col-sm-3 col-sm-offset-9">
      <div class="new-post-btn">
        <% if can? :crud, Post %>
          <%= link_to "New post", new_post_path, class: "btn btn-default new-post-btn"%>
          <% end %>
      </div>
    </div>
  </div>

      <div class="row post-row">
      <% @posts.each do |post| %>
      <div class="col-lg-4 col-md-6 col-sm-12 post-col">
        <%= form_for @cart_item, remote: true do |f| %>
          <div class="post-content">
            <div class="text-center">
              <div class="post-title">
                <h2 style="text-align: center"><%= link_to post.title, post_path(post), style: "color: black" %></h2>
                  </div>
                  <h6><%= link_to Category.find(post.category_id).name, category_path(post.category_id) %> by <%= link_to post.user.username, post.user %> on: <%= post.created_at.strftime('%b %d, %Y') %></h6>
                </div>
                <div class="post-image-index">
                  <% if post.image? %>
                    <div class="media">
                      <div class="media-left">
                        <%= link_to image_tag(post.image.url(:medium), class: 'media-object'), post.image.url, class:"img-rounded", target: '_blank' %>
                        <% if can? :crud, Post %>
                          <%= link_to "Remove image", delete_post_image_path(post), data: { confirm: 'Are you sure you want to remove this image?' }, class: "btn btn-danger btn-xs" %>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                </div>
                &nbsp;

                <div class="post-body">
                  <%= raw(post.body).truncate(358) %>
                </div>
                <% if post.body.size > 358 %>
                <div class="text-center">
                  <%= link_to "READ MORE", post_path(post), class: "btn btn-sm"%>
                </div>
                <% end %>
                <div class="add-to-cart-btn">
                  <h4 class="text-right">Price:
                  <% if post.price.nil? %>
                    <span style="color: green">Free</span></h4>
                  <% else %>  
                    <span style="color: green"><%= number_to_currency post.price %></span></h4>
                  <% end %>
                  <div class="input-group">
                    <%= f.number_field :quantity, value: 1, class: "form-control", min: 1, style: "width: 50px; float: right" %>
                    <div class="input-group-btn">
                      <%= f.hidden_field :post_id, value: post.id %>
                      <%= f.submit "Add to Cart", class: "btn btn-primary" %>
                    </div>
                  </div>
                </div>
                <hr>
                <div class="post-buttons">
                <div class="post-buttons-left" style="float: left">
                <% if can? :crud, post %>
                  <%= link_to "Edit", edit_post_path(post), class: "btn btn-default btn-sm" %>
                  <%= link_to "Delete", post_path(post),
                    method: :delete,
                    data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"%>
                  <% end %>
                    </div>
                  <div class="post-buttons-right" style="float: right">
                      <div class="comment-button" style="float: right">
                        <%= link_to post_path(post, anchor: "comment-section"), class: "btn btn-default btn-sm", title: "Show comments" do %>
                        <span class="glyphicon glyphicon-comment" style="color: grey"></span>
                        <%= post.comments.count %>
                      <% end %>
                      </div>
                      <div class="favorite-button" style="float: right">
                      <% if current_user %>
                        <% if post.favorited_by.exists?(current_user.id) %>
                          <%= link_to favorite_post_path(post, type: "unfavorite"), method: :put, class: "btn btn-default btn-sm", title: "Remove from favorites" do %>
                          <span class="glyphicon glyphicon-star" style="color: #ffbb33"></span>
                          <% end %>
                        <% else %>
                          <%= link_to favorite_post_path(post, type: "favorite"), method: :put, class: "btn btn-default btn-sm", title: "Add to favorites" do %>
                          <span class="glyphicon glyphicon-star" style="color: grey"></span>
                          <% end %>
                        <% end %>
                      <% end %>
                    <!-- form_for cart_item -->
                    <% end %>
                  </div>
                </div>
              </div>
            <br>
            </div>
            </div>
    <% end %>
    </div>
    </div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-sm-12">
			<h1>Create new post</h1>

			<%= render "posts/form" %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12 post-content">
			<div class="post-header">
			<h1><%= @post.title %></h1>
			<h5><%= @post.category.name %> by <%= link_to @post.user.username, user_path(@post.user) %></h5>
			<h6>On <%= @post.created_at.strftime('%b %d, %Y at %H:%M') %></h6>
			</div>
			<hr>
			<% if @post.image? %>
				<div class="media">
					<div class="media-center">
						<%= link_to image_tag(@post.image.url(:medium), class: 'media-object'), @post.image.url, class:"img-rounded", target: '_blank' %>
						<%= link_to "Remove image", delete_post_image_path, data: { confirm: 'Are you sure?' } %>
					</div>
				</div>
			<% end %>
			<%= raw @post.body %>
			<hr>
			<% if can? :crud, Comment %>
			<div id="comment-section" class="comment-section-post">
				<h6>Add a comment</h6>
				<%= render partial: "comments/form", locals: {commentable: @post} %>
			</div>
			<% end %>
			<div class="comment-section-post">
				<h6>Comments</h6>
				<%= render partial: "comments/comments", locals: {commentable: @post} %>
			</div>
			<div class="show-post-buttons">
				<%= link_to "Back", posts_path, class: "btn btn-default btn-sm" %>
				<% if can? :crud, @post %>
					<%= link_to "Edit", edit_post_path, class: "btn btn-default btn-sm" %>
					<%= link_to "Delete", post_path(@post),
						method: :delete,
						data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
				<% end %>
			</div>
		</div>
	</div>
</div>