config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/create'

  get 'cart_items/update'

  get 'cart_items/destroy'

  get 'carts/show'

  devise_for :users

  resource :cart, only: [:show]
  resources :cart_items, only: [:create, :update, :destroy], defaults: { format: 'js' }

  resources :users, :only => [:show]

  resources :posts, :categories

  resources :posts do
    put :favorite, on: :member
  end

  resources :favorites, :only => [:index]

  resources :posts do
    resources :comments, module: :posts
  end

  resources :comments

  get 'posts/:id/delete_image', to: 'posts#delete_image', as: 'delete_post_image'

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  get 'welcome', to: 'pages#welcome' 

  root 'posts#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	load_and_authorize_resource
	
	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		@category.save
		render :show
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category.update_attributes(category_params)
		redirect_to categories_path(@category)
	end

	def show
		@category = Category.find(params[:id])
		@posts = Post.where(category_id: @category.id)
	end

	def destroy
	end

	def category_params
		params.require(:category).permit(:name, :desc)
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@category.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_area :desc, class: "form-control" %>
  </div>

  <div class="form-group">
    <% if current_page?(new_category_path) %>
      <%= f.submit "Create Category" %>
    <% elsif current_page?(edit_category_path) %>
      <%= f.submit "Update Category", class: "btn btn-default" %>
    <% end %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="wrapper">
<div class="container">
<h1>Edit Category</h1>

<%= render "categories/form" %>
</div>
</div>

app/views/categories/index.html.erb
<div class="wrapper">
	<div class="container">
		<div class="content-section">
			<div class="row">
				<div class="col-sm-6">
					<% @categories.each do |category| %>
					<h4><%= link_to category.name, category_path(category) %></h4>
					<p><%= category.desc %></p>
					<hr>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "categories/form" %>

app/views/categories/show.html.erb
<div class="wrapper">
	<div class="container">
		<h3>Posts under <%= @category.name %> category:</h3>
		<h6>Showing <%= @posts.count %> posts</h6>
		&nbsp;
		<div class="content-section">
			<% @posts.each do |post| %>
			<div class="post-image">
				<% unless post.image.url.present? %>
					<%= image_tag(post.image.url) %>
				<% end %>
			</div>
			<h5><%= link_to post.title, post_path(post) %>&nbsp;<%= post.price %></h5>
			<h6><%= raw(post.body).truncate(150) %></h6>
			<%= link_to "Read more", post_path(post), class: "btn btn-xs" %>
			<hr>
			<% end %>
		</div>
	</div>
</div>